### ISSUE TITLE
java.lang.OutOfMemoryError: pthread_create 

### ISSUE THREAD

**Issue by abahe** [muddassir235/connection_checker#1]
I got this error 

java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
        at java.lang.Thread.nativeCreate(Native Method)
        at java.lang.Thread.start(Thread.java:883)
        at com.android.volley.RequestQueue.start(RequestQueue.java:134)
        at com.android.volley.toolbox.Volley.newRequestQueue(Volley.java:91)
        at com.android.volley.toolbox.Volley.newRequestQueue(Volley.java:67)
        at com.android.volley.toolbox.Volley.newRequestQueue(Volley.java:102)
        at com.muddassir.connection_checker.MacrosKt.pingUrl(macros.kt:12)
        at com.muddassir.connection_checker.ConnectionChecker.evaluateConnection(ConnectionChecker.kt:58)
        at com.muddassir.connection_checker.ConnectionChecker.check(ConnectionChecker.kt:43)
        at com.muddassir.connection_checker.ConnectionChecker.access$check(ConnectionChecker.kt:29)
        at com.muddassir.connection_checker.ConnectionChecker$checkAgain$$inlined$delay$1.run(functions.kt:23)

**Comment by muddassir235** [comment]
Thank you for your feedback and raising this issue. Will look into this and get back to you (~3 working days)

**Comment by muddassir235** [comment]
@abahe In the meanwhile it would be great to know the details of the device/emulator the app is running on.

**Comment by abahe** [comment]
> @abahe In the meanwhile it would be great to know the details of the device/emulator the app is running on.

Samsung Galaxy M20
Android 10

**Comment by muddassir235** [comment]
@abahe Kindly use version 1.7

**Comment by muddassir235** [comment]
@abahe Kindly use version 1.7

**Comment by abahe** [comment]
thank you
